export const STAGES = [
  { id: 'foundation', name: 'Foundation' },
  { id: 'core_language', name: 'Core Language' },
  { id: 'vocabulary', name: 'Vocabulary' },
  { id: 'getting_around', name: 'Getting Around' },
  { id: 'fluency', name: 'Fluency' },
  { id: 'advanced', name: 'Advanced' },
];

export const CATEGORIES = [
  { id: 'greetings_and_courtesies', name: 'Greetings & Courtesies', stage: 'foundation' },
  { id: 'basic_everyday_expressions', name: 'Basic Everyday Expressions', stage: 'foundation' },
  { id: 'time_and_availability', name: 'Time & Availability', stage: 'foundation' },
  { id: 'ability_and_refusal', name: 'Ability & Refusal', stage: 'foundation' },
  { id: 'agreement_and_politeness', name: 'Agreement & Politeness', stage: 'foundation' },
  { id: 'personal_information', name: 'Personal Information', stage: 'foundation' },
  { id: 'numbers_and_time', name: 'Numbers & Time', stage: 'foundation' },
  { id: 'social_and_goodbye', name: 'Social & Goodbye', stage: 'foundation' },
  { id: 'everyday_verbs', name: 'Everyday Verbs', stage: 'core_language' },
  { id: 'grammar_building_blocks', name: 'Grammar Building Blocks', stage: 'core_language' },
  { id: 'actions_and_requests', name: 'Actions & Requests', stage: 'core_language' },
  { id: 'knowledge_and_opinion', name: 'Knowledge & Opinion', stage: 'core_language' },
  { id: 'home_and_environment', name: 'Home & Environment', stage: 'vocabulary' },
  { id: 'food_and_dining', name: 'Food & Dining', stage: 'vocabulary' },
  { id: 'shopping', name: 'Shopping', stage: 'vocabulary' },
  { id: 'work_and_school', name: 'Work & School', stage: 'vocabulary' },
  { id: 'hearing_and_noise', name: 'Hearing & Noise', stage: 'vocabulary' },
  { id: 'movement_and_plans', name: 'Movement & Plans', stage: 'vocabulary' },
  { id: 'weather_and_physical_states', name: 'Weather & Physical States', stage: 'vocabulary' },
  { id: 'travel_and_directions', name: 'Travel & Directions', stage: 'getting_around' },
  { id: 'hobbies_and_leisure', name: 'Hobbies & Leisure', stage: 'fluency' },
  { id: 'social_communication', name: 'Social Communication', stage: 'fluency' },
  { id: 'feelings_and_health', name: 'Feelings & Health', stage: 'fluency' },
  { id: 'memory_and_forgetting', name: 'Memory & Forgetting', stage: 'fluency' },
  { id: 'preferences_and_decisions', name: 'Preferences & Decisions', stage: 'fluency' },
  { id: 'statements_and_situations', name: 'Statements & Situations', stage: 'fluency' },
  { id: 'encouragement_and_care', name: 'Encouragement & Care', stage: 'fluency' },
  { id: 'past_tense', name: 'Past Tense', stage: 'advanced' },
];
